/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-container-high": "#e7e8e9",
        "outline-variant": "#c3c6d7",
        "error": "#ba1a1a",
        "tertiary": "#943700",
        "secondary": "#585f6c",
        "on-surface": "#191c1d",
        "on-primary": "#ffffff",
        "on-surface-variant": "#434655",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f0f1f2",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary-container": "#eeefff",
        "text-primary": "#111827",
        "error-container": "#ffdad6",
        "tertiary-container": "#bc4800",
        "info": "#0EA5E9",
        "on-background": "#191c1d",
        "background": "#FAFBFC",
        "surface-container-low": "#f3f4f5",
        "on-primary-fixed-variant": "#003ea8",
        "on-tertiary-container": "#ffede6",
        "surface-tint": "#0053db",
        "primary": "#2563EB",
        "surface-secondary": "#F5F7FA",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#00174b",
        "warning": "#F59E0B",
        "secondary-fixed-dim": "#c0c7d6",
        "on-error": "#ffffff",
        "secondary-fixed": "#dce2f3",
        "danger": "#EF4444",
        "tertiary-fixed": "#ffdbcd",
        "on-secondary-fixed-variant": "#404754",
        "surface-dim": "#d9dadb",
        "surface-container": "#edeeef",
        "surface": "#FFFFFF",
        "outline": "#737686",
        "surface-bright": "#f8f9fa",
        "primary-fixed": "#dbe1ff",
        "border": "#E5E7EB",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#151c27",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#dce2f3",
        "primary-container": "#2563eb",
        "inverse-primary": "#b4c5ff",
        "text-secondary": "#6B7280",
        "surface-variant": "#e1e3e4",
        "inverse-surface": "#2e3132",
        "on-tertiary-fixed": "#360f00",
        "success": "#22C55E",
        "on-tertiary-fixed-variant": "#7d2d00",
        "on-secondary-container": "#5e6572",
        "tertiary-fixed-dim": "#ffb596",
        "surface-container-highest": "#e1e3e4"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "container-max": "1440px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "base": "4px"
      },
      "fontFamily": {
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "display-lg": ["Inter"],
        "headline-md": ["Inter"],
        "code-sm": ["jetbrainsMono"],
        "headline-lg-mobile": ["Inter"],
        "label-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"]
      },
      "fontSize": {
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
        "display-lg": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-md": ["20px", {"lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "code-sm": ["13px", {"lineHeight": "18px", "fontWeight": "400"}],
        "headline-lg-mobile": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-lg": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
